[theme]
base = "light"
primaryColor = "#1a73e8"  # Azul Google
backgroundColor = "#f5f5f5"  # Gris claro
secondaryBackgroundColor = "#ffffff"  # Fondo de la tarjeta
textColor = "#202124"  # Negro grisáceo
font = "monospace"
